import type { NicheConfig } from "@/types";

export const NICHE_CONFIG: Record<string, NicheConfig> = {
  barbearia: {
    label: "Barbearia",
    cta: "Agende seu horário",
    tone: "Moderno e direto",
    services: ["Corte masculino", "Barba", "Sobrancelha", "Acabamento", "Progressiva"],
    description: "Barbearia especializada em cortes modernos e clássicos",
    calendarTopics: {
      dica: "dica de cuidado com o cabelo em casa",
      servico: "destaque do serviço de corte + barba",
      chamada: "agenda aberta — chame no WhatsApp",
      educativo: "como escolher o corte ideal para seu rosto",
      promocao: "promoção da semana — corte + barba",
      relacionamento: "bom dia, barbearia pronta para te atender",
      autoridade: "por que fazer manutenção regular do cabelo",
      bastidores: "bastidores da barbearia",
      oferta: "oferta especial de fim de semana",
      lembrete: "lembrete: sua barba precisa de atenção",
      prova: "resultado do nosso trabalho — corte impecável",
      chamadaFinal: "últimos horários da semana — agende agora",
    },
  },
  odontologia: {
    label: "Odontologia",
    cta: "Agende sua avaliação",
    tone: "Profissional e confiável",
    services: ["Limpeza dental", "Clareamento", "Restauração", "Implante", "Aparelho"],
    description: "Cuidado completo do seu sorriso com atenção e profissionalismo",
    calendarTopics: {
      dica: "dica de higiene bucal para o dia a dia",
      servico: "limpeza dental — quando foi a última vez?",
      chamada: "avaliação gratuita — chame no WhatsApp",
      educativo: "o que causa a sensibilidade nos dentes",
      promocao: "clareamento com condição especial",
      relacionamento: "sorriso bonito começa com cuidado diário",
      autoridade: "por que ir ao dentista a cada 6 meses",
      bastidores: "estrutura da nossa clínica para te receber",
      oferta: "consulta de avaliação esta semana",
      lembrete: "lembrete: não adie o cuidado do seu sorriso",
      prova: "transformações reais — cuidado de quem entende",
      chamadaFinal: "últimas vagas da semana — agende já",
    },
  },
  "clinica-medica": {
    label: "Clínica Médica",
    cta: "Fale com a clínica",
    tone: "Responsável e informativo",
    services: ["Consulta clínica", "Exames", "Acompanhamento", "Prevenção", "Saúde geral"],
    description: "Atendimento médico com responsabilidade e dedicação",
    calendarTopics: {
      dica: "dica de saúde preventiva para o dia a dia",
      servico: "consultas com atendimento humanizado",
      chamada: "marque sua consulta pelo WhatsApp",
      educativo: "cuidados importantes que você pode estar ignorando",
      promocao: "agende sua consulta de acompanhamento",
      relacionamento: "saúde em dia é qualidade de vida",
      autoridade: "por que exames preventivos fazem diferença",
      bastidores: "nossa equipe dedicada ao seu cuidado",
      oferta: "consultas disponíveis esta semana",
      lembrete: "lembrete: check-up anual em dia",
      prova: "cuidando de cada paciente com dedicação",
      chamadaFinal: "não adie sua saúde — agende agora",
    },
  },
  otica: {
    label: "Ótica / Oculista",
    cta: "Fale com um consultor",
    tone: "Claro e confiável",
    services: ["Armações", "Lentes", "Óculos de sol", "Lentes de contato", "Ajuste"],
    description: "Sua visão em boas mãos com produtos de qualidade",
    calendarTopics: {
      dica: "como cuidar dos seus óculos corretamente",
      servico: "armações modernas para todos os estilos",
      chamada: "fale com um consultor pelo WhatsApp",
      educativo: "quando é hora de trocar as lentes dos óculos",
      promocao: "condição especial em armações selecionadas",
      relacionamento: "ver bem é viver melhor",
      autoridade: "a importância do exame de vista regular",
      bastidores: "conheça nossa seleção de armações",
      oferta: "lentes com proteção UV — essa semana",
      lembrete: "quando foi seu último exame de vista?",
      prova: "qualidade e cuidado em cada atendimento",
      chamadaFinal: "venha nos visitar — consultor disponível",
    },
  },
  "personal-trainer": {
    label: "Personal Trainer",
    cta: "Comece seu acompanhamento",
    tone: "Motivador e energético",
    services: ["Treino personalizado", "Consultoria online", "Emagrecimento", "Hipertrofia", "Condicionamento"],
    description: "Treinamento personalizado para conquistar seus objetivos",
    calendarTopics: {
      dica: "dica de treino para fazer em qualquer lugar",
      servico: "treino personalizado para o seu objetivo",
      chamada: "comece agora — chame no WhatsApp",
      educativo: "erro comum que sabota o resultado na academia",
      promocao: "condição especial para novos alunos",
      relacionamento: "motivação para a semana — você consegue!",
      autoridade: "por que treino sem acompanhamento gera resultado menor",
      bastidores: "veja como é o acompanhamento personalizado",
      oferta: "primeira semana de treino com condição especial",
      lembrete: "não pule o treino — consistência é tudo",
      prova: "resultados reais com acompanhamento profissional",
      chamadaFinal: "vagas abertas essa semana — agende agora",
    },
  },
  estetica: {
    label: "Estética",
    cta: "Agende seu atendimento",
    tone: "Bonito e profissional",
    services: ["Limpeza de pele", "Sobrancelha", "Depilação", "Massagem", "Tratamentos faciais"],
    description: "Cuidados estéticos profissionais com atenção personalizada",
    calendarTopics: {
      dica: "dica de skincare para fazer em casa",
      servico: "limpeza de pele profissional",
      chamada: "agende seu horário pelo WhatsApp",
      educativo: "como cuidar da pele no dia a dia",
      promocao: "promoção especial de limpeza de pele",
      relacionamento: "cuidar de você é um ato de amor",
      autoridade: "por que limpeza de pele profissional é diferente",
      bastidores: "nosso espaço preparado para te receber",
      oferta: "horário especial disponível esta semana",
      lembrete: "quando foi seu último atendimento de pele?",
      prova: "resultados visíveis com tratamento profissional",
      chamadaFinal: "últimos horários da semana — agende agora",
    },
  },
  "loja-roupa": {
    label: "Loja de Roupa",
    cta: "Chame no WhatsApp",
    tone: "Comercial e estiloso",
    services: ["Moda feminina", "Moda masculina", "Kids", "Acessórios", "Novidades semanais"],
    description: "Moda com estilo e qualidade para todos os momentos",
    calendarTopics: {
      dica: "dica de como montar looks versáteis",
      servico: "novidades que chegaram essa semana",
      chamada: "chame no WhatsApp e veja as peças",
      educativo: "como combinar cores e estampar sem errar",
      promocao: "promoção da semana — peças selecionadas",
      relacionamento: "você merece se sentir bonita/o",
      autoridade: "tendências que estão dominando essa temporada",
      bastidores: "veja as novidades chegando na loja",
      oferta: "frete grátis para pedidos acima de X reais",
      lembrete: "você precisa ver o que chegou hoje",
      prova: "clientes que amaram os looks daqui",
      chamadaFinal: "últimas peças disponíveis — não perde!",
    },
  },
  imobiliaria: {
    label: "Imobiliária",
    cta: "Fale com um corretor",
    tone: "Seguro e profissional",
    services: ["Compra de imóveis", "Venda", "Aluguel", "Avaliação", "Financiamento"],
    description: "Seu imóvel ideal com segurança e transparência",
    calendarTopics: {
      dica: "dica para quem está buscando o primeiro imóvel",
      servico: "imóveis disponíveis para compra e aluguel",
      chamada: "fale com um corretor pelo WhatsApp",
      educativo: "como funciona o processo de financiamento",
      promocao: "imóveis em destaque esta semana",
      relacionamento: "encontrar o lar ideal começa por aqui",
      autoridade: "por que escolher um corretor de confiança",
      bastidores: "nos bastidores de uma negociação bem-sucedida",
      oferta: "imóvel novo disponível — consulte agora",
      lembrete: "o imóvel que você busca pode estar disponível",
      prova: "mais um cliente satisfeito com a negociação",
      chamadaFinal: "aproveite as oportunidades desta semana",
    },
  },
  restaurante: {
    label: "Restaurante",
    cta: "Faça seu pedido",
    tone: "Convidativo e saboroso",
    services: ["Almoço", "Jantar", "Delivery", "Marmita", "Reservas"],
    description: "Sabor e qualidade em cada refeição",
    calendarTopics: {
      dica: "dica de como aproveitar o almoço com qualidade",
      servico: "prato especial do dia — veja o cardápio",
      chamada: "peça pelo WhatsApp — delivery disponível",
      educativo: "por que comer bem faz diferença no dia",
      promocao: "promoção do dia — combinação especial",
      relacionamento: "obrigado por escolher nosso restaurante",
      autoridade: "ingredientes frescos e selecionados para você",
      bastidores: "cozinha preparando o prato do dia",
      oferta: "combo especial — almoço + sobremesa",
      lembrete: "já pensou no almoço de hoje?",
      prova: "sabor aprovado pelos nossos clientes",
      chamadaFinal: "reserve sua mesa para o fim de semana",
    },
  },
  mecanica: {
    label: "Mecânica",
    cta: "Solicite um orçamento",
    tone: "Confiável e direto",
    services: ["Revisão geral", "Troca de óleo", "Freios", "Suspensão", "Diagnóstico eletrônico"],
    description: "Seu veículo nas mãos de quem entende",
    calendarTopics: {
      dica: "dica de manutenção preventiva para o seu carro",
      servico: "revisão completa com preço justo",
      chamada: "solicite orçamento pelo WhatsApp",
      educativo: "sinais que indicam que seu carro precisa de revisão",
      promocao: "troca de óleo com condição especial",
      relacionamento: "cuidar do carro é garantir sua segurança",
      autoridade: "por que a manutenção preventiva economiza dinheiro",
      bastidores: "nossa equipe técnica cuidando do seu veículo",
      oferta: "diagnóstico eletrônico gratuito esta semana",
      lembrete: "quando foi a última revisão do seu carro?",
      prova: "mais um veículo saindo em perfeito estado",
      chamadaFinal: "agende sua revisão — horários disponíveis",
    },
  },
  serralheria: {
    label: "Serralheria",
    cta: "Peça um orçamento",
    tone: "Prático e profissional",
    services: ["Portões", "Grades", "Estruturas metálicas", "Escadas", "Manutenção"],
    description: "Serviços em ferro e aço com qualidade e durabilidade",
    calendarTopics: {
      dica: "dica de manutenção para portões e grades",
      servico: "portões e grades com acabamento profissional",
      chamada: "solicite orçamento pelo WhatsApp",
      educativo: "como escolher o portão ideal para seu imóvel",
      promocao: "condição especial para portão automático",
      relacionamento: "segurança e beleza para a sua casa",
      autoridade: "por que escolher aço galvanizado de qualidade",
      bastidores: "fabricação própria com controle de qualidade",
      oferta: "orçamento gratuito e sem compromisso",
      lembrete: "seu portão precisa de manutenção?",
      prova: "resultado do trabalho — qualidade e durabilidade",
      chamadaFinal: "solicite orçamento ainda esta semana",
    },
  },
  advogacia: {
    label: "Advocacia / Escritório Jurídico",
    cta: "Agende uma consulta",
    tone: "Profissional, sério e confiável",
    services: ["Consultoria jurídica", "Direito trabalhista", "Direito de família", "Direito do consumidor", "Assessoria preventiva", "Contratos"],
    description: "Assessoria jurídica profissional para defender seus direitos com segurança",
    calendarTopics: {
      dica: "direito que todo cidadão deveria conhecer",
      servico: "quando você precisa de um advogado",
      chamada: "consulta disponível — chame no WhatsApp",
      educativo: "como funciona um processo na prática",
      promocao: "consulta inicial — esclareça suas dúvidas",
      relacionamento: "seu problema jurídico tem solução",
      autoridade: "por que ter um advogado de confiança faz diferença",
      bastidores: "como trabalhamos por cada caso",
      oferta: "consulta disponível essa semana",
      lembrete: "não deixe seu problema jurídico crescer",
      prova: "mais um caso resolvido com dedicação",
      chamadaFinal: "últimas vagas da semana — agende já",
    },
  },
  psicologia: {
    label: "Psicologia / Terapia",
    cta: "Agende sua sessão",
    tone: "Acolhedor, empático e profissional",
    services: ["Psicoterapia individual", "Terapia de casal", "Orientação vocacional", "Saúde mental", "Acompanhamento psicológico"],
    description: "Acompanhamento psicológico humanizado para quem busca equilíbrio emocional",
    calendarTopics: {
      dica: "dica de saúde mental para o dia a dia",
      servico: "como funciona a psicoterapia",
      chamada: "sessão disponível — chame no WhatsApp",
      educativo: "como a terapia pode mudar sua vida",
      promocao: "primeira sessão — veja como funciona",
      relacionamento: "cuidar da saúde mental é amor próprio",
      autoridade: "por que o acompanhamento psicológico é importante",
      bastidores: "como é uma sessão de terapia na prática",
      oferta: "sessão disponível essa semana",
      lembrete: "sua saúde mental importa — não adie",
      prova: "cuidando de cada pessoa com atenção real",
      chamadaFinal: "vagas abertas essa semana — agende já",
    },
  },
  contabilidade: {
    label: "Contabilidade / Escritório Contábil",
    cta: "Fale com um contador",
    tone: "Confiável, prático e direto",
    services: ["Abertura de empresa", "Declaração de IR", "Folha de pagamento", "BPO financeiro", "MEI", "Contabilidade mensal"],
    description: "Contabilidade confiável para manter sua empresa regularizada e pagar menos imposto",
    calendarTopics: {
      dica: "dica fiscal para não pagar imposto a mais",
      servico: "contabilidade que sua empresa precisa",
      chamada: "análise gratuita — chame no WhatsApp",
      educativo: "o que MEI precisa saber sobre imposto",
      promocao: "análise contábil gratuita essa semana",
      relacionamento: "empresa organizada é empresa que cresce",
      autoridade: "por que um bom contador economiza dinheiro",
      bastidores: "como trabalhamos pela saúde financeira da sua empresa",
      oferta: "atendimento disponível essa semana",
      lembrete: "prazo de declaração se aproximando — regularize agora",
      prova: "mais um cliente com empresa regularizada",
      chamadaFinal: "não deixe para a última hora — fale agora",
    },
  },
  "salao-beleza": {
    label: "Salão de Beleza",
    cta: "Agende seu horário",
    tone: "Elegante e acolhedor",
    services: ["Corte feminino", "Coloração", "Escova", "Progressiva", "Manicure", "Pedicure"],
    description: "Beleza e cuidado completo para você se sentir incrível",
    calendarTopics: {
      dica: "dica de cuidado com os cabelos em casa",
      servico: "transformação completa — corte e coloração",
      chamada: "agende seu horário pelo WhatsApp",
      educativo: "como manter a coloração durando mais",
      promocao: "promoção especial de coloração esta semana",
      relacionamento: "você merece se sentir linda todos os dias",
      autoridade: "por que cuidar do cabelo com profissional faz diferença",
      bastidores: "transformações reais que fazemos todo dia",
      oferta: "combo especial — corte + escova",
      lembrete: "quando foi a última vez que você se cuidou?",
      prova: "resultado real — antes e depois no salão",
      chamadaFinal: "últimos horários da semana — agende agora",
    },
  },
  "pet-shop": {
    label: "Pet Shop / Veterinária",
    cta: "Agende para seu pet",
    tone: "Carinhoso e confiável",
    services: ["Banho e tosa", "Consulta veterinária", "Vacinação", "Hospedagem", "Rações e acessórios"],
    description: "Cuidado completo e carinhoso para o seu melhor amigo",
    calendarTopics: {
      dica: "dica de cuidado com seu pet em casa",
      servico: "banho e tosa com carinho e qualidade",
      chamada: "agende para seu pet pelo WhatsApp",
      educativo: "sinais de que seu pet precisa de atenção veterinária",
      promocao: "promoção de banho e tosa esta semana",
      relacionamento: "seu pet merece o melhor cuidado",
      autoridade: "por que cuidados regulares fazem seu pet mais saudável",
      bastidores: "nosso espaço preparado com amor para os pets",
      oferta: "primeira consulta com condição especial",
      lembrete: "vacinas em dia = pet saudável e protegido",
      prova: "mais um petinho saindo lindo e feliz",
      chamadaFinal: "agende agora — horários disponíveis esta semana",
    },
  },
  fisioterapia: {
    label: "Fisioterapia / Pilates",
    cta: "Agende sua avaliação",
    tone: "Técnico, acolhedor e motivador",
    services: ["Fisioterapia ortopédica", "Pilates", "RPG", "Reabilitação", "Pré e pós-operatório"],
    description: "Recuperação e qualidade de vida com tratamento especializado",
    calendarTopics: {
      dica: "exercício simples para aliviar dor nas costas",
      servico: "avaliação fisioterapêutica — primeiro passo para recuperar",
      chamada: "agende sua avaliação pelo WhatsApp",
      educativo: "quando a dor precisa de fisioterapia",
      promocao: "avaliação gratuita esta semana",
      relacionamento: "cada caso é único — cuidamos de você com atenção",
      autoridade: "por que reabilitação profissional acelera a recuperação",
      bastidores: "estrutura completa para sua recuperação",
      oferta: "pacote de sessões com condição especial",
      lembrete: "não ignore a dor — procure ajuda especializada",
      prova: "pacientes que recuperaram a qualidade de vida",
      chamadaFinal: "vagas abertas esta semana — agende agora",
    },
  },
  nutricao: {
    label: "Nutrição",
    cta: "Agende sua consulta",
    tone: "Educativo, acolhedor e motivador",
    services: ["Consulta nutricional", "Plano alimentar", "Emagrecimento", "Nutrição esportiva", "Reeducação alimentar"],
    description: "Alimentação inteligente para você atingir seus objetivos com saúde",
    calendarTopics: {
      dica: "dica de alimentação saudável para o dia a dia",
      servico: "plano alimentar personalizado para o seu objetivo",
      chamada: "agende sua consulta pelo WhatsApp",
      educativo: "por que dietas restritivas não funcionam a longo prazo",
      promocao: "consulta com condição especial esta semana",
      relacionamento: "alimentação é cuidado — você merece o melhor",
      autoridade: "diferença entre nutricionista e dieta da internet",
      bastidores: "como é uma consulta de nutrição na prática",
      oferta: "avaliação nutricional com desconto especial",
      lembrete: "o que você come hoje define sua saúde amanhã",
      prova: "resultados reais com acompanhamento nutricional",
      chamadaFinal: "vagas disponíveis esta semana — agende já",
    },
  },
  fotografia: {
    label: "Fotografia / Filmagem",
    cta: "Solicite um orçamento",
    tone: "Criativo e profissional",
    services: ["Ensaio fotográfico", "Casamento", "Newborn", "Corporativo", "Vídeo social media"],
    description: "Momentos únicos registrados com arte e sensibilidade",
    calendarTopics: {
      dica: "dica para posar melhor nas fotos",
      servico: "ensaio fotográfico — registre esse momento",
      chamada: "solicite orçamento pelo WhatsApp",
      educativo: "como preparar para um ensaio fotográfico",
      promocao: "sessão fotográfica com condição especial",
      relacionamento: "cada foto conta uma história única",
      autoridade: "por que contratar fotógrafo profissional faz diferença",
      bastidores: "bastidores de um ensaio fotográfico real",
      oferta: "pacote especial para essa semana",
      lembrete: "não deixe esse momento importante passar sem registro",
      prova: "registros reais — veja nosso trabalho",
      chamadaFinal: "datas limitadas — garanta a sua agora",
    },
  },
  construcao: {
    label: "Construção / Reforma",
    cta: "Solicite um orçamento",
    tone: "Confiável, direto e profissional",
    services: ["Reforma completa", "Pintura", "Revestimento", "Elétrica", "Hidráulica", "Acabamento"],
    description: "Construção e reforma com qualidade, prazo e transparência",
    calendarTopics: {
      dica: "dica para manter sua casa valorizada",
      servico: "reforma com qualidade e prazo garantido",
      chamada: "solicite orçamento pelo WhatsApp",
      educativo: "como planejar uma reforma sem surpresas no orçamento",
      promocao: "orçamento gratuito esta semana",
      relacionamento: "transformamos espaços, realizamos sonhos",
      autoridade: "por que contratar profissional evita prejuízo",
      bastidores: "nossa equipe em mais uma obra entregue",
      oferta: "orçamento sem compromisso — chame agora",
      lembrete: "aquela reforma que você está adiando pode começar agora",
      prova: "obra entregue — resultado que fala por si",
      chamadaFinal: "agenda aberta — solicite orçamento hoje",
    },
  },
  confeitaria: {
    label: "Confeitaria / Padaria",
    cta: "Faça seu pedido",
    tone: "Carinhoso, artesanal e convidativo",
    services: ["Bolos personalizados", "Doces finos", "Brigadeiros", "Tortas", "Encomendas"],
    description: "Sabor artesanal feito com carinho para adoçar seus momentos",
    calendarTopics: {
      dica: "dica de como conservar doces e bolos",
      servico: "bolo personalizado para o seu evento",
      chamada: "faça seu pedido pelo WhatsApp",
      educativo: "como escolher o bolo certo para cada ocasião",
      promocao: "combo especial de doces para eventos",
      relacionamento: "feito com carinho para adoçar seu dia",
      autoridade: "diferença entre confeitaria artesanal e industrial",
      bastidores: "nos bastidores da produção — tudo feito à mão",
      oferta: "encomenda especial com desconto essa semana",
      lembrete: "aquela data especial está chegando — encomende já",
      prova: "mais um pedido entregue com carinho e capricho",
      chamadaFinal: "poucas datas disponíveis — reserve a sua",
    },
  },
  coaching: {
    label: "Coaching / Mentoria",
    cta: "Agende uma sessão",
    tone: "Inspirador, direto e transformador",
    services: ["Coaching individual", "Mentoria de negócios", "Desenvolvimento pessoal", "Coaching de carreira", "Grupo de mentoria"],
    description: "Resultados reais através de clareza, foco e ação estratégica",
    calendarTopics: {
      dica: "hábito simples que muda sua produtividade",
      servico: "sessão de coaching — clareza para agir",
      chamada: "agende uma conversa pelo WhatsApp",
      educativo: "diferença entre coaching, mentoria e terapia",
      promocao: "sessão gratuita de diagnóstico essa semana",
      relacionamento: "sua transformação começa com uma decisão",
      autoridade: "por que pessoas de sucesso investem em mentoria",
      bastidores: "bastidores de uma sessão de coaching na prática",
      oferta: "programa especial com vagas limitadas",
      lembrete: "o que você está esperando para mudar de vida?",
      prova: "resultado real de quem investiu em desenvolvimento",
      chamadaFinal: "vagas limitadas — inscreva-se agora",
    },
  },
  "escola-cursos": {
    label: "Escola / Cursos",
    cta: "Garanta sua vaga",
    tone: "Educativo, motivador e acolhedor",
    services: ["Cursos presenciais", "Aulas online", "Turmas particulares", "Certificação", "Workshop"],
    description: "Conhecimento que transforma vidas e abre portas",
    calendarTopics: {
      dica: "dica de aprendizado para absorver mais conteúdo",
      servico: "conheça nossos cursos e turmas disponíveis",
      chamada: "garanta sua vaga pelo WhatsApp",
      educativo: "por que aprender uma habilidade nova muda sua vida",
      promocao: "matrícula com condição especial essa semana",
      relacionamento: "aprender é o melhor investimento que existe",
      autoridade: "nossa metodologia e resultados dos alunos",
      bastidores: "como são nossas aulas na prática",
      oferta: "primeira aula gratuita — sem compromisso",
      lembrete: "novas turmas começando — garante logo sua vaga",
      prova: "alunos que transformaram sua vida com nosso curso",
      chamadaFinal: "últimas vagas — inscreva-se agora",
    },
  },
  tatuagem: {
    label: "Tatuagem / Piercing",
    cta: "Agende seu atendimento",
    tone: "Criativo, autêntico e profissional",
    services: ["Tatuagem personalizada", "Cover up", "Piercing", "Micro tattoo", "Blackwork"],
    description: "Arte na pele feita com técnica, higiene e criatividade",
    calendarTopics: {
      dica: "cuidados essenciais com tatuagem recente",
      servico: "tatuagem personalizada — sua ideia na pele",
      chamada: "agende pelo WhatsApp — orçamento sem compromisso",
      educativo: "como escolher o local certo para tatuar",
      promocao: "peça especial com condição essa semana",
      relacionamento: "cada tatuagem conta uma história única",
      autoridade: "por que higiene e técnica fazem toda diferença",
      bastidores: "processo de criação de uma tatuagem personalizada",
      oferta: "orçamento de peça especial essa semana",
      lembrete: "aquela tattoo que você sempre quis — hora de fazer",
      prova: "trabalhos reais saídos do nosso estúdio",
      chamadaFinal: "agenda com poucas datas — garanta a sua",
    },
  },
  outro: {
    label: "Outro negócio local",
    cta: "Fale conosco",
    tone: "Neutro e profissional",
    services: ["Atendimento personalizado", "Consulta", "Orçamento", "Produtos", "Serviços"],
    description: "Atendimento profissional com qualidade e dedicação",
    calendarTopics: {
      dica: "dica útil para clientes do nosso segmento",
      servico: "conheça nosso serviço principal",
      chamada: "fale com a gente pelo WhatsApp",
      educativo: "informação importante sobre nossos serviços",
      promocao: "condição especial desta semana",
      relacionamento: "obrigado por confiar no nosso trabalho",
      autoridade: "por que somos a escolha certa para você",
      bastidores: "nos bastidores do nosso trabalho",
      oferta: "oferta disponível esta semana",
      lembrete: "lembrete importante para você",
      prova: "qualidade comprovada em cada atendimento",
      chamadaFinal: "fale agora pelo WhatsApp",
    },
  },
};

export const NICHE_OPTIONS = Object.entries(NICHE_CONFIG).map(([value, config]) => ({
  value,
  label: config.label,
}));
