import type { NicheConfig } from "@/types";

export const NICHE_CONFIG: Record<string, NicheConfig> = {
  barbearia: {
    label: "Barbearia",
    cta: "Agende seu horário",
    tone: "Moderno e direto",
    services: ["Corte masculino", "Barba", "Sobrancelha", "Acabamento", "Progressiva"],
    description: "Barbearia especializada em cortes modernos e clássicos",
    calendarTopics: {
      dica: "dica de cuidado com o cabelo em casa",
      servico: "destaque do serviço de corte + barba",
      chamada: "agenda aberta — chame no WhatsApp",
      educativo: "como escolher o corte ideal para seu rosto",
      promocao: "promoção da semana — corte + barba",
      relacionamento: "bom dia, barbearia pronta para te atender",
      autoridade: "por que fazer manutenção regular do cabelo",
      bastidores: "bastidores da barbearia",
      oferta: "oferta especial de fim de semana",
      lembrete: "lembrete: sua barba precisa de atenção",
      prova: "resultado do nosso trabalho — corte impecável",
      chamadaFinal: "últimos horários da semana — agende agora",
    },
  },
  odontologia: {
    label: "Odontologia",
    cta: "Agende sua avaliação",
    tone: "Profissional e confiável",
    services: ["Limpeza dental", "Clareamento", "Restauração", "Implante", "Aparelho"],
    description: "Cuidado completo do seu sorriso com atenção e profissionalismo",
    calendarTopics: {
      dica: "dica de higiene bucal para o dia a dia",
      servico: "limpeza dental — quando foi a última vez?",
      chamada: "avaliação gratuita — chame no WhatsApp",
      educativo: "o que causa a sensibilidade nos dentes",
      promocao: "clareamento com condição especial",
      relacionamento: "sorriso bonito começa com cuidado diário",
      autoridade: "por que ir ao dentista a cada 6 meses",
      bastidores: "estrutura da nossa clínica para te receber",
      oferta: "consulta de avaliação esta semana",
      lembrete: "lembrete: não adie o cuidado do seu sorriso",
      prova: "transformações reais — cuidado de quem entende",
      chamadaFinal: "últimas vagas da semana — agende já",
    },
  },
  "clinica-medica": {
    label: "Clínica Médica",
    cta: "Fale com a clínica",
    tone: "Responsável e informativo",
    services: ["Consulta clínica", "Exames", "Acompanhamento", "Prevenção", "Saúde geral"],
    description: "Atendimento médico com responsabilidade e dedicação",
    calendarTopics: {
      dica: "dica de saúde preventiva para o dia a dia",
      servico: "consultas com atendimento humanizado",
      chamada: "marque sua consulta pelo WhatsApp",
      educativo: "cuidados importantes que você pode estar ignorando",
      promocao: "agende sua consulta de acompanhamento",
      relacionamento: "saúde em dia é qualidade de vida",
      autoridade: "por que exames preventivos fazem diferença",
      bastidores: "nossa equipe dedicada ao seu cuidado",
      oferta: "consultas disponíveis esta semana",
      lembrete: "lembrete: check-up anual em dia",
      prova: "cuidando de cada paciente com dedicação",
      chamadaFinal: "não adie sua saúde — agende agora",
    },
  },
  otica: {
    label: "Ótica / Oculista",
    cta: "Fale com um consultor",
    tone: "Claro e confiável",
    services: ["Armações", "Lentes", "Óculos de sol", "Lentes de contato", "Ajuste"],
    description: "Sua visão em boas mãos com produtos de qualidade",
    calendarTopics: {
      dica: "como cuidar dos seus óculos corretamente",
      servico: "armações modernas para todos os estilos",
      chamada: "fale com um consultor pelo WhatsApp",
      educativo: "quando é hora de trocar as lentes dos óculos",
      promocao: "condição especial em armações selecionadas",
      relacionamento: "ver bem é viver melhor",
      autoridade: "a importância do exame de vista regular",
      bastidores: "conheça nossa seleção de armações",
      oferta: "lentes com proteção UV — essa semana",
      lembrete: "quando foi seu último exame de vista?",
      prova: "qualidade e cuidado em cada atendimento",
      chamadaFinal: "venha nos visitar — consultor disponível",
    },
  },
  "personal-trainer": {
    label: "Personal Trainer",
    cta: "Comece seu acompanhamento",
    tone: "Motivador e energético",
    services: ["Treino personalizado", "Consultoria online", "Emagrecimento", "Hipertrofia", "Condicionamento"],
    description: "Treinamento personalizado para conquistar seus objetivos",
    calendarTopics: {
      dica: "dica de treino para fazer em qualquer lugar",
      servico: "treino personalizado para o seu objetivo",
      chamada: "comece agora — chame no WhatsApp",
      educativo: "erro comum que sabota o resultado na academia",
      promocao: "condição especial para novos alunos",
      relacionamento: "motivação para a semana — você consegue!",
      autoridade: "por que treino sem acompanhamento gera resultado menor",
      bastidores: "veja como é o acompanhamento personalizado",
      oferta: "primeira semana de treino com condição especial",
      lembrete: "não pule o treino — consistência é tudo",
      prova: "resultados reais com acompanhamento profissional",
      chamadaFinal: "vagas abertas essa semana — agende agora",
    },
  },
  estetica: {
    label: "Estética",
    cta: "Agende seu atendimento",
    tone: "Bonito e profissional",
    services: ["Limpeza de pele", "Sobrancelha", "Depilação", "Massagem", "Tratamentos faciais"],
    description: "Cuidados estéticos profissionais com atenção personalizada",
    calendarTopics: {
      dica: "dica de skincare para fazer em casa",
      servico: "limpeza de pele profissional",
      chamada: "agende seu horário pelo WhatsApp",
      educativo: "como cuidar da pele no dia a dia",
      promocao: "promoção especial de limpeza de pele",
      relacionamento: "cuidar de você é um ato de amor",
      autoridade: "por que limpeza de pele profissional é diferente",
      bastidores: "nosso espaço preparado para te receber",
      oferta: "horário especial disponível esta semana",
      lembrete: "quando foi seu último atendimento de pele?",
      prova: "resultados visíveis com tratamento profissional",
      chamadaFinal: "últimos horários da semana — agende agora",
    },
  },
  "loja-roupa": {
    label: "Loja de Roupa",
    cta: "Chame no WhatsApp",
    tone: "Comercial e estiloso",
    services: ["Moda feminina", "Moda masculina", "Kids", "Acessórios", "Novidades semanais"],
    description: "Moda com estilo e qualidade para todos os momentos",
    calendarTopics: {
      dica: "dica de como montar looks versáteis",
      servico: "novidades que chegaram essa semana",
      chamada: "chame no WhatsApp e veja as peças",
      educativo: "como combinar cores e estampar sem errar",
      promocao: "promoção da semana — peças selecionadas",
      relacionamento: "você merece se sentir bonita/o",
      autoridade: "tendências que estão dominando essa temporada",
      bastidores: "veja as novidades chegando na loja",
      oferta: "frete grátis para pedidos acima de X reais",
      lembrete: "você precisa ver o que chegou hoje",
      prova: "clientes que amaram os looks daqui",
      chamadaFinal: "últimas peças disponíveis — não perde!",
    },
  },
  imobiliaria: {
    label: "Imobiliária",
    cta: "Fale com um corretor",
    tone: "Seguro e profissional",
    services: ["Compra de imóveis", "Venda", "Aluguel", "Avaliação", "Financiamento"],
    description: "Seu imóvel ideal com segurança e transparência",
    calendarTopics: {
      dica: "dica para quem está buscando o primeiro imóvel",
      servico: "imóveis disponíveis para compra e aluguel",
      chamada: "fale com um corretor pelo WhatsApp",
      educativo: "como funciona o processo de financiamento",
      promocao: "imóveis em destaque esta semana",
      relacionamento: "encontrar o lar ideal começa por aqui",
      autoridade: "por que escolher um corretor de confiança",
      bastidores: "nos bastidores de uma negociação bem-sucedida",
      oferta: "imóvel novo disponível — consulte agora",
      lembrete: "o imóvel que você busca pode estar disponível",
      prova: "mais um cliente satisfeito com a negociação",
      chamadaFinal: "aproveite as oportunidades desta semana",
    },
  },
  restaurante: {
    label: "Restaurante",
    cta: "Faça seu pedido",
    tone: "Convidativo e saboroso",
    services: ["Almoço", "Jantar", "Delivery", "Marmita", "Reservas"],
    description: "Sabor e qualidade em cada refeição",
    calendarTopics: {
      dica: "dica de como aproveitar o almoço com qualidade",
      servico: "prato especial do dia — veja o cardápio",
      chamada: "peça pelo WhatsApp — delivery disponível",
      educativo: "por que comer bem faz diferença no dia",
      promocao: "promoção do dia — combinação especial",
      relacionamento: "obrigado por escolher nosso restaurante",
      autoridade: "ingredientes frescos e selecionados para você",
      bastidores: "cozinha preparando o prato do dia",
      oferta: "combo especial — almoço + sobremesa",
      lembrete: "já pensou no almoço de hoje?",
      prova: "sabor aprovado pelos nossos clientes",
      chamadaFinal: "reserve sua mesa para o fim de semana",
    },
  },
  mecanica: {
    label: "Mecânica",
    cta: "Solicite um orçamento",
    tone: "Confiável e direto",
    services: ["Revisão geral", "Troca de óleo", "Freios", "Suspensão", "Diagnóstico eletrônico"],
    description: "Seu veículo nas mãos de quem entende",
    calendarTopics: {
      dica: "dica de manutenção preventiva para o seu carro",
      servico: "revisão completa com preço justo",
      chamada: "solicite orçamento pelo WhatsApp",
      educativo: "sinais que indicam que seu carro precisa de revisão",
      promocao: "troca de óleo com condição especial",
      relacionamento: "cuidar do carro é garantir sua segurança",
      autoridade: "por que a manutenção preventiva economiza dinheiro",
      bastidores: "nossa equipe técnica cuidando do seu veículo",
      oferta: "diagnóstico eletrônico gratuito esta semana",
      lembrete: "quando foi a última revisão do seu carro?",
      prova: "mais um veículo saindo em perfeito estado",
      chamadaFinal: "agende sua revisão — horários disponíveis",
    },
  },
  serralheria: {
    label: "Serralheria",
    cta: "Peça um orçamento",
    tone: "Prático e profissional",
    services: ["Portões", "Grades", "Estruturas metálicas", "Escadas", "Manutenção"],
    description: "Serviços em ferro e aço com qualidade e durabilidade",
    calendarTopics: {
      dica: "dica de manutenção para portões e grades",
      servico: "portões e grades com acabamento profissional",
      chamada: "solicite orçamento pelo WhatsApp",
      educativo: "como escolher o portão ideal para seu imóvel",
      promocao: "condição especial para portão automático",
      relacionamento: "segurança e beleza para a sua casa",
      autoridade: "por que escolher aço galvanizado de qualidade",
      bastidores: "fabricação própria com controle de qualidade",
      oferta: "orçamento gratuito e sem compromisso",
      lembrete: "seu portão precisa de manutenção?",
      prova: "resultado do trabalho — qualidade e durabilidade",
      chamadaFinal: "solicite orçamento ainda esta semana",
    },
  },
  outro: {
    label: "Outro negócio local",
    cta: "Fale conosco",
    tone: "Neutro e profissional",
    services: ["Atendimento personalizado", "Consulta", "Orçamento", "Produtos", "Serviços"],
    description: "Atendimento profissional com qualidade e dedicação",
    calendarTopics: {
      dica: "dica útil para clientes do nosso segmento",
      servico: "conheça nosso serviço principal",
      chamada: "fale com a gente pelo WhatsApp",
      educativo: "informação importante sobre nossos serviços",
      promocao: "condição especial desta semana",
      relacionamento: "obrigado por confiar no nosso trabalho",
      autoridade: "por que somos a escolha certa para você",
      bastidores: "nos bastidores do nosso trabalho",
      oferta: "oferta disponível esta semana",
      lembrete: "lembrete importante para você",
      prova: "qualidade comprovada em cada atendimento",
      chamadaFinal: "fale agora pelo WhatsApp",
    },
  },
};

export const NICHE_OPTIONS = Object.entries(NICHE_CONFIG).map(([value, config]) => ({
  value,
  label: config.label,
}));
